name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Pack
      run: nuget pack ./stackage-aws-lambda-templates.nuspec -NoDefaultExcludes -Version ${VERSION}

    - name: Install Lambda Template
      run: dotnet new --install ./Stackage.Aws.Lambda.DotNetNew.Templates.${VERSION}.nupkg

  # TODO: Create shared workflow to test individual framework

    - name: Use Lambda Template (net6.0)
      run: dotnet new stackagelambda --name Lambda.Function.Six.Zero --framework net6.0
    - name: Build Generated Lambda (net6.0)
      working-directory: ./Lambda.Function.Six.Zero
      shell: pwsh
      run: ./build-package.ps1

    - name: Use Lambda Template (net8.0)
      run: dotnet new stackagelambda --name Lambda.Function.Eight.Zero --framework net8.0
    - name: Build Generated Lambda (net8.0)
      working-directory: ./Lambda.Function.Eight.Zero
      shell: pwsh
      run: ./build-package.ps1

    - name: Push
      run: dotnet nuget push Stackage.*.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.STACKAGE_NUGET_PUSH_TOKEN }}
